# Basic colors
foreground #FFF3DC
background #16161C
selection_foreground #16161C
selection_background #FFF3DC

# Cursor colors
cursor #F43E5C
cursor_text_color #2C2A24

# URL underline color when hovering with mouse
url_color #7699A3

# Kitty window border colors
active_border_color #A0907A
inactive_border_color #3A372F

# OS Window titlebar colors
wayland_titlebar_color #16161C
macos_titlebar_color #16161C

# Tab bar colors
active_tab_foreground #2C2A24
active_tab_background #DDD5C4
inactive_tab_foreground #A0907A
inactive_tab_background #3A372F
tab_bar_background #2C2A24

# Colors for marks (marked text in the terminal)
mark1_foreground #2C2A24
mark1_background #D08B57
mark2_foreground #2C2A24
mark2_background #8D7AAE
mark3_foreground #2C2A24
mark3_background #78997A