include colors.conf

# Font
font_family Iosevka Nerd Font Mono
bold_italic_font auto
font_size 14.0

# Window
window_padding_width 0 0 0 12
hide_window_decorations no
confirm_os_window_close 0
background_opacity 0.9
background_blur 4

# Allow remote access
allow_remote_control yes

# Cursor
cursor_blink_interval 0

#Shell integrations
shell_integration no-title no-cursor
